# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Till Hovestadt
email: till.hovestadt@nuffield.ox.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Data Scientist - Sociologist - PhD Student, University of Oxford
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tillhovestadt.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Nuffield College
address_line: New Road, OX1 1NF Oxford, United Kingdom
#elephone_number: 1.800.245.356
#fax_number: 1.800.245.357
company_email: till.hovestadt "at" nuffield.ox.ac.uk
google_map: https://maps.app.goo.gl/1aFouLKCtK8JMypp9

# Social Link
#facebook_link: http://www.facebook.com
#twitter_link: http://www.twitter.com
linkedin_link: https://www.linkedin.com/in/till-hovestadt-613020207/
#googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
